---
swagger: "2.0"
info:
  version: "2017-02-08T03:28:39Z"
  title: "LambdaMicroservice"
host: "5bscn4ze4i.execute-api.us-west-2.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /LambdaPoc:
    x-amazon-apigateway-any-method:
      responses:
        200:
          description: "200 response"
      security:
      - sigv4: []
securityDefinitions:
  sigv4:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "awsSigv4"
